# Generated by Django 4.2 on 2024-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('booking_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('hotel_id', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DailyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('booking_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('hotel_id', 'date')},
            },
        ),
    ]
